#define I_ADD_OP_1                0
#define I_ADD_OP_2                32
#define I_ADDU_OP_1               0
#define I_ADDU_OP_2               33
#define I_ADDI_OP_1               8
#define I_ADDIU_OP_1              9
#define I_AND_OP_1                0
#define I_AND_OP_2                36
#define I_ANDI_OP_1               12
#define I_CLO_OP_1                28
#define I_CLO_OP_2                33
#define I_CLZ_OP_1                28
#define I_CLZ_OP_2                32
#define I_DIV_OP_1                0
#define I_DIV_OP_2                26
#define I_DIVU_OP_1               0
#define I_DIVU_OP_2               27
#define I_MULT_OP_1               0
#define I_MULT_OP_2               24
#define I_MULTU_OP_1              0
#define I_MULTU_OP_2              25
#define I_MUL_OP_1                28
#define I_MUL_OP_2                2
#define I_MADD_OP_1               28
#define I_MADD_OP_2               0
#define I_MADDU_OP_1              28
#define I_MADDU_OP_2              1
#define I_MSUB_OP_1               28
#define I_MSUB_OP_2               4
#define I_MSUBU_OP_1              28
#define I_MSUBU_OP_2              5
#define I_NOR_OP_1                0
#define I_NOR_OP_2                39
#define I_OR_OP_1                 0
#define I_OR_OP_2                 37
#define I_ORI_OP_1                13
#define I_SLL_OP_1                0
#define I_SLL_OP_2                0
#define I_SLLV_OP_1               0
#define I_SLLV_OP_2               4
#define I_SRA_OP_1                0
#define I_SRA_OP_2                7
#define I_SRL_OP_1                0
#define I_SRL_OP_2                2
#define I_SRLV_OP_1               0
#define I_SRLV_OP_2               6
#define I_SUB_OP_1                0
#define I_SUB_OP_2                34
#define I_SUBU_OP_1               0
#define I_SUBU_OP_2               35
#define I_XOR_OP_1                0
#define I_XOR_OP_2                38
#define I_XORI_OP_1               14
#define I_LUI_OP_1                15
#define I_SLT_OP_1                0
#define I_SLT_OP_2                42
#define I_SLTU_OP_1               0
#define I_SLTU_OP_2               43
#define I_SLTI_OP_1               10
#define I_SLTIU_OP_1              11
#define I_BCLF_OP_1               17
#define I_BCLF_OP_2               8
#define I_BCLT_OP_1               17
#define I_BCLT_OP_2               8
#define I_BEQ_OP_1                4
#define I_BGEZ_OP_1               1
#define I_BGEZ_OP_2               1
#define I_BGEZAL_OP_1             1
#define I_BGEZAL_OP_2             17
#define I_BGTZ_OP_1               7
#define I_BLEZ_OP_1               6
#define I_BLTZAL_OP_1             1
#define I_BLTZAL_OP_2             16
#define I_BLTZ_OP_1               1
#define I_BNE_OP_1                5
#define I_J_OP_1                  2
#define I_JAL_OP_1                3
#define I_JALR_OP_1               0
#define I_JALR_OP_2               9
#define I_JR_OP_1                 0
#define I_JR_OP_2                 8
#define I_TEQ_OP_1                0
#define I_TEQ_OP_2                52
#define I_TEQI_OP_1               1
#define I_TEQI_OP_2               12
#define I_TNE_OP_1                0
#define I_TNE_OP_2                54
#define I_TNEI_OP_1               1
#define I_TNEI_OP_2               14
#define I_TGE_OP_1                0
#define I_TGE_OP_2                48
#define I_TGEU_OP_1               0
#define I_TGEU_OP_2               49
#define I_TGEI_OP_1               1
#define I_TGEI_OP_2               8
#define I_TGEIU_OP_1              1
#define I_TGEIU_OP_2              9
#define I_TLT_OP_1                0
#define I_TLT_OP_2                50
#define I_TLTU_OP_1               0
#define I_TLTU_OP_2               51
#define I_TLTI_OP_1               1
#define I_TLTI_OP_2               10
#define I_TLTIU_OP_1              1
#define I_TLTIU_OP_2              11
#define I_LB_OP_1                 32
#define I_LBU_OP_1                36
#define I_LH_OP_1                 33
#define I_LHU_OP_1                37
#define I_LW_OP_1                 35
#define I_LWCL_OP_1               49
#define I_LWL_OP_1                34
#define I_LWR_OP_1                38
#define I_LL_OP_1                 48
#define I_SB_OP_1                 40
#define I_SB_OP_1                 41
#define I_SB_OP_1                 43
#define I_SB_OP_1                 49
#define I_SB_OP_1                 61
#define I_SB_OP_1                 42
#define I_SB_OP_1                 46
#define I_SC_OP_1                 56
#define I_MFHI_OP_1               0
#define I_MFHI_OP_2               16
#define I_MFLO_OP_1               0
#define I_MFLO_OP_2               18
#define I_MTHI_OP_1               0
#define I_MTHI_OP_2               17
#define I_MTLO_OP_1               0
#define I_MTLO_OP_2               19
#define I_MFC0_OP_1               16
#define I_MFC0_OP_2               0
#define I_MFC1_OP_1               17
#define I_MFC1_OP_2               0
#define I_MTC0_OP_1               16
#define I_MTC0_OP_2               0
#define I_MTC0_OP_3               4
#define I_MTC1_OP_1               17
#define I_MTC1_OP_2               0
#define I_MTC1_OP_3               4
#define I_MOVN_OP_1               0
#define I_MOVN_OP_2               11
#define I_MOVZ_OP_1               0
#define I_MOVZ_OP_2               10
#define I_MOVF_OP_1               0
#define I_MOVF_OP_2               1
#define I_MOVT_OP_1               0
#define I_MOVT_OP_2               1
#define I_ABS_D_OP_1              17
#define I_ABS_D_OP_2              5
#define I_ABS_D_OP_3              1
#define I_ABS_S_OP_1              17
#define I_ABS_S_OP_2              5
#define I_ADD_D_OP_1              17
#define I_ADD_D_OP_2              0
#define I_ADD_D_OP_3              17
#define I_ADD_S_OP_1              17
#define I_ADD_S_OP_2              0
#define I_ADD_S_OP_3              16
#define I_CEIL_W_D_OP_1           17
#define I_CEIL_W_D_OP_2           14
#define I_CEIL_W_D_OP_3           17
#define I_CEIL_W_S_OP_1           17
#define I_CEIL_W_S_OP_2           14
#define I_CEIL_W_S_OP_3           16
#define I_C_EQ_D_OP_1             17
#define I_C_EQ_D_OP_2             2
#define I_C_EQ_D_OP_3             17
#define I_C_EQ_S_OP_1             17
#define I_C_EQ_S_OP_2             2
#define I_C_EQ_S_OP_3             16
#define I_C_LE_D_OP_1             17
#define I_C_LE_D_OP_2             14
#define I_C_LE_D_OP_3             17
#define I_C_LE_S_OP_1             17
#define I_C_LE_S_OP_2             14
#define I_C_LE_S_OP_3             16
#define I_C_LT_D_OP_1             17
#define I_C_LT_D_OP_2             12
#define I_C_LT_D_OP_3             17
#define I_C_LT_S_OP_1             17
#define I_C_LT_S_OP_2             12
#define I_C_LT_S_OP_3             16
#define I_CVT_D_S_OP_1            17
#define I_CVT_D_S_OP_2            33
#define I_CVT_D_S_OP_3            16
#define I_CVT_D_W_OP_1            17
#define I_CVT_D_W_OP_2            33
#define I_CVT_D_W_OP_3            20
#define I_CVT_S_D_OP_1            17
#define I_CVT_S_D_OP_2            32
#define I_CVT_S_D_OP_3            17
#define I_CVT_S_W_OP_1            17
#define I_CVT_S_W_OP_2            32
#define I_CVT_S_W_OP_3            20
#define I_CVT_W_D_OP_1            17
#define I_CVT_W_D_OP_2            36
#define I_CVT_W_D_OP_3            17
#define I_CVT_W_S_OP_1            17
#define I_CVT_W_S_OP_2            36
#define I_CVT_W_S_OP_3            16
#define I_DIV_D_OP_1              17
#define I_DIV_D_OP_2              3
#define I_DIV_D_OP_3              17
#define I_DIV_S_OP_1              17
#define I_DIV_S_OP_2              3
#define I_DIV_S_OP_3              16
#define I_FLOOR_W_D_OP_1          17
#define I_FLOOR_W_D_OP_2          15
#define I_FLOOR_W_D_OP_3          17
#define I_FLOOR_W_S_OP_1          17
#define I_FLOOR_W_S_OP_2          15
#define I_FLOOR_W_S_OP_3          16
#define I_MOV_D_OP_1              17
#define I_MOV_D_OP_2              6
#define I_MOV_D_OP_3              17
#define I_MOV_S_OP_1              17
#define I_MOV_S_OP_2              6
#define I_MOV_S_OP_3              16
#define I_MOVF_D_OP_1             17
#define I_MOVF_D_OP_2             17
#define I_MOVF_D_OP_3             17
#define I_MOVF_S_OP_1             17
#define I_MOVF_S_OP_2             17
#define I_MOVF_S_OP_3             16
#define I_MOVT_D_OP_1             17
#define I_MOVT_D_OP_2             17
#define I_MOVT_D_OP_3             17
#define I_MOVT_S_OP_1             17
#define I_MOVT_S_OP_2             17
#define I_MOVT_S_OP_3             16
#define I_MOVN_D_OP_1             17
#define I_MOVN_D_OP_2             19
#define I_MOVN_D_OP_3             17
#define I_MOVN_S_OP_1             17
#define I_MOVN_S_OP_2             19
#define I_MOVN_S_OP_3             16
#define I_MOVZ_D_OP_1             17
#define I_MOVZ_D_OP_2             18
#define I_MOVZ_D_OP_3             17
#define I_MOVZ_D_OP_1             17
#define I_MOVZ_D_OP_2             18
#define I_MOVZ_D_OP_3             16
#define I_MUL_D_OP_1              17
#define I_MUL_D_OP_2              2
#define I_MUL_D_OP_3              17
#define I_MUL_S_OP_1              17
#define I_MUL_S_OP_2              2
#define I_MUL_S_OP_3              16
#define I_NEG_D_OP_1              17
#define I_NEG_D_OP_2              7
#define I_NEG_D_OP_3              17
#define I_NEG_S_OP_1              17
#define I_NEG_S_OP_2              7
#define I_NEG_S_OP_3              16
#define I_ROUND_W_D_OP_1          17
#define I_ROUND_W_D_OP_2          12
#define I_ROUND_W_D_OP_3          17
#define I_ROUDN_W_S_OP_1          17
#define I_ROUDN_W_S_OP_2          12
#define I_ROUDN_W_S_OP_3          16
#define I_SQRT_D_OP_1             17
#define I_SQRT_D_OP_2             4
#define I_SQRT_D_OP_3             17
#define I_SQRT_S_OP_1             17
#define I_SQRT_S_OP_2             4
#define I_SQRT_S_OP_3             16
#define I_SUB_D_OP_1              17
#define I_SUB_D_OP_2              1
#define I_SUB_D_OP_3              17
#define I_SUB_S_OP_1              17
#define I_SUB_S_OP_2              1
#define I_SUB_S_OP_3              16
#define I_TRUNC_W_D_OP_1          17
#define I_TRUNC_W_D_OP_2          13
#define I_TRUNC_W_D_OP_3          17
#define I_TRUNC_W_S_OP_1          17
#define I_TRUNC_W_S_OP_2          13
#define I_TRUNC_W_S_OP_3          16
#define I_ERET_OP_1               0
#define I_ERET_OP_2               24
#define I_ERET_OP_3               16
#define I_SYSCALL_OP_1            0
#define I_SYSCALL_OP_2            12
#define I_NOP_OP_1                0
#define I_NOP_OP_2                0
