#define I_ABS                0
#define I_ADD                1
#define I_ADDU               2
#define I_ADDI               3
#define I_ADDIU              4
#define I_AND                5
#define I_ANDI               6
#define I_CLO                7
#define I_CLZ                8
#define I_DIV                9
#define I_DIVU               10
#define I_MULT               11
#define I_MULTU              12
#define I_MUL                13
#define I_MADD               14
#define I_MADDU              15
#define I_MSUB               16
#define I_MSUBU              17
#define I_NEG                18
#define I_NOR                19
#define I_NOT                20
#define I_OR                 21
#define I_ORI                22
#define I_SLL                23
#define I_SLLV               24
#define I_SRA                25
#define I_SRL                26
#define I_SRLV               27
#define I_SUB                28
#define I_SUBU               29
#define I_XOR                30
#define I_XORI               31
#define I_LUI                32
#define I_LI                 33
#define I_SLT                34
#define I_SLTU               35
#define I_SLTI               36
#define I_SLTIU              37
#define I_SGE                38
#define I_SGT                39
#define I_B                  40
#define I_BCLF               41
#define I_BCLT               42
#define I_BEQ                43
#define I_BGEZ               44
#define I_BGEZAL             45
#define I_BGTZ               46
#define I_BLEZ               47
#define I_BLTZAL             48
#define I_BLTZ               49
#define I_BNE                50
#define I_BEQZ               51
#define I_BGE                52
#define I_BGEU               53
#define I_BGT                54
#define I_BGTU               55
#define I_BLE                56
#define I_BLEU               57
#define I_BLT                58
#define I_BLTU               59
#define I_BNEZ               60
#define I_J                  61
#define I_JAL                62
#define I_JALR               63
#define I_JR                 64
#define I_TEQ                65
#define I_TEQI               66
#define I_TNE                67
#define I_TNEI               68
#define I_TGE                69
#define I_TGEU               70
#define I_TGEI               71
#define I_TGEIU              72
#define I_TLT                73
#define I_TLTU               74
#define I_TLTI               75
#define I_TLTIU              76
#define I_LA                 77
#define I_LB                 78
#define I_LBU                79
#define I_LH                 80
#define I_LHU                81
#define I_LW                 82
#define I_LWCL               83
#define I_LWL                84
#define I_LWR                85
#define I_LD                 86
#define I_LL                 87
#define I_SB                 88
#define I_SB                 89
#define I_SB                 90
#define I_SB                 91
#define I_SB                 92
#define I_SB                 93
#define I_SB                 94
#define I_SD                 95
#define I_SC                 96
#define I_MOVE               97
#define I_MFHI               98
#define I_MFLO               99
#define I_MTHI               100
#define I_MTLO               101
#define I_MFC0               102
#define I_MFC1               103
#define I_MFCL_D             104
#define I_MTC0               105
#define I_MTC1               106
#define I_MOVN               107
#define I_MOVZ               108
#define I_MOVF               109
#define I_MOVT               110
#define I_ABS_D              111
#define I_ABS_S              112
#define I_ADD_D              113
#define I_ADD_S              114
#define I_CEIL_W_D           115
#define I_CEIL_W_S           116
#define I_C_EQ_D             117
#define I_C_EQ_S             118
#define I_C_LE_D             119
#define I_C_LE_S             120
#define I_C_LT_D             121
#define I_C_LT_S             122
#define I_CVT_D_S            123
#define I_CVT_D_W            124
#define I_CVT_S_D            125
#define I_CVT_S_W            126
#define I_CVT_W_D            127
#define I_CVT_W_S            128
#define I_DIV_D              129
#define I_DIV_S              130
#define I_FLOOR_W_D          131
#define I_FLOOR_W_S          132
#define I_MOV_D              133
#define I_MOV_S              134
#define I_MOVF_D             135
#define I_MOVF_S             136
#define I_MOVT_D             137
#define I_MOVT_S             138
#define I_MOVN_D             139
#define I_MOVN_S             140
#define I_MOVZ_D             141
#define I_MOVZ_D             142
#define I_MUL_D              143
#define I_MUL_S              144
#define I_NEG_D              145
#define I_NEG_S              146
#define I_ROUND_W_D          147
#define I_ROUDN_W_S          148
#define I_SQRT_D             149
#define I_SQRT_S             150
#define I_SUB_D              151
#define I_SUB_S              152
#define I_TRUNC_W_D          153
#define I_TRUNC_W_S          154
#define I_ERET               155
#define I_SYSCALL            156
#define I_NOP                157
